name = "TemplateMatchingCLI"
uuid = "4afe5421-88a9-4a08-b622-ce50c7f41406"
authors = ["Stefano Campanella <15182642+stefanocampanella@users.noreply.github.com> and contributors"]
version = "0.1.0"

[compat]
julia = "1.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
